version: "3.7"

services: 

  db:
    image: postgres:13.1
    restart: always
    container_name: postgres-db
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes: 
      - ./scripts:/docker-entrypoint-initdb.d
    networks: 
      - internal

  pgadmin:
    image: dpage/pgadmin4:4.29
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    networks: 
      - internal
    depends_on: 
      - "db"

networks: 
  internal: 
    driver: bridge